---
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect    hibernate:      ddl-auto: create
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:    console:      enabled: true
      path: /h2-console

server:
  port: 8080
  